version: '3.4'

services:
  rssnodeangular:
    image: rssnodeangular
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
  mongo:
      image: mongo
      ports:
      - 27017:27017
      volumes:
      - mongodb:/data/db
volumes:
 mongodb: